version: 2.1

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - carthage-cache-mbdirections-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
          - carthage-cache-mbdirections-v1- # used if checksum fails

  - &save-cache
      save_cache:
        key: carthage-cache-mbdirections-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

  - &prepare
      run:
        name: Prepare
        command: |
          if [ $(carthage outdated | grep -cF "latest Carthage version") -eq 0 ]; then brew update && brew upgrade carthage || true; fi
          echo "foo" > ~/.mapbox

jobs:
  build-job:
    parameters:
      xcode:
        type: string
      device:
        type: string
        default: "iPhone 6 Plus"
      iOS:
        type: string
        default: "12.1"
      watchOS:
        type: string
        default: "5.0"
      tvOS:
        type: string
        default: "12.0"
      test:
        type: boolean
        default: true
      codecoverage:
        type: boolean
        default: false
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - *prepare
      - *restore-cache
      - run:
          name: iOS
          command: |
            carthage bootstrap --platform ios --cache-builds --no-use-binaries --new-resolver
            xcodebuild -sdk iphonesimulator -project MapboxDirections.xcodeproj -scheme 'MapboxDirections iOS' -destination 'platform=iOS Simulator,OS=<< parameters.iOS >>,name=<< parameters.device >>' clean build <<# parameters.test >>test <</ parameters.test >> <<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>  
      - run:
          name: tvOS
          command: |
            carthage bootstrap --platform tvos --cache-builds --no-use-binaries --new-resolver
            xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=<< parameters.tvOS >>' clean build <<# parameters.test >>test <</ parameters.test >> <<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - run:
          name: macOS
          command: |
            carthage bootstrap --platform macos --cache-builds --no-use-binaries --new-resolver
            xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections Mac' clean build<<# parameters.test >> test <</ parameters.test >><<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - run:
          name: watchOS
          command: |
            carthage bootstrap --platform watchos --cache-builds --no-use-binaries --new-resolver
            xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch Series 3 - 42mm,OS=<< parameters.watchOS >>' clean build
      - when:
          condition: << parameters.codecoverage >>
          steps:
            - run: bash <(curl -s https://codecov.io/bash)
      - *save-cache           

workflows:
  workflow:
    jobs:
      - build-job:
          name: "Xcode_10.2"
          xcode: "10.2.0"
          iOS: "12.2"
          tvOS: "12.2"
          watchOS: "5.2"
          codecoverage: true
      - build-job:
          name: "Xcode_10.0"
          xcode: "10.0.0"
          iOS: "12.0"
          tvOS: "12.0"
      - build-job:
          name: "Xcode_9.4"
          xcode: "9.4.1"
          iOS: "10.3.1"
          tvOS: "11.4"
          watchOS: "4.3"
